import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { data } from "../../lib/data";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title> Shopwith-J | Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <Link href="/about">About</Link>
        <div className="">
          <div className="">
            <div className="">
              <div className="text-white">
                <h1 className="mb-3">Steak House</h1>
                <h4 className="mb-3">A premium and authentic steak house</h4>
                {/* <a
                className="btn btn-outline-light btn-lg m-2"
                href="#!"
                role="button"
                >See menu</a
              >
              <a
                className="btn btn-outline-light btn-lg m-2"
                href="#!"
                role="button"
                >Book a table</a
              > */}
              </div>
            </div>
          </div>
        </div>
      </main>
      {data.map((item) => (
        <Link href={`/display/${item.id}`}>
          <div className="card" key={item.id}>
            <h1 className="title">{item.name}</h1>
            <Image
              src={`/${item.image}`}
              alt="Vercel Logo"
              width={400}
              height={400}
            />
            <p>{item.description}</p>
          </div>
        </Link>
      ))}

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
